apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: default
  labels:
    app: weather-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: weather-app
  type: NodePort